package se.rmsit.TicTacToe.display;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class ResultPanel {
	private JTextArea txtAreaResult;
	private JPanel panelResult;
	// Singleton, resultat ska bara hanteras av en instans.
	private static ResultPanel instance;
	private int xVictories = 0;
	private int oVictories = 0;

	public ResultPanel() {
		instance = this;
	}

	public static void addResult(char player, String message) {
		if (player == 'x')
			instance.xVictories++;
		else if (player == 'o')
			instance.oVictories++;
		instance.txtAreaResult.append("Spelare " + Character.toUpperCase(player) + " vann på " + message + "\n");
		instance.txtAreaResult.append(getScoreMessage() + "\n");
	}

	public static String getScoreMessage() {
		return "Score(X:O) " + getXVictories() + ":" + getOVictories();
	}

	// getters and setters
	public static int getXVictories() {
		return instance.xVictories;
	}

	public static int getOVictories() {
		return instance.oVictories;
	}

	public static void addDraw() {
		instance.txtAreaResult.append("Oavgjort\n");
		instance.txtAreaResult.append(getScoreMessage() + "\n");
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		panelResult = new JPanel();
		panelResult.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
		final JScrollPane scrollPane1 = new JScrollPane();
		panelResult.add(scrollPane1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		txtAreaResult = new JTextArea();
		txtAreaResult.setEditable(false);
		txtAreaResult.setEnabled(true);
		txtAreaResult.setText("");
		scrollPane1.setViewportView(txtAreaResult);
		final JLabel label1 = new JLabel();
		label1.setText("Wins");
		panelResult.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTH, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return panelResult;
	}
}
